// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt81FYlfHiatIdpjsWx79mHPDCxSg8Zzg',
    appId: '1:49160994700:web:f555e6667c5a95ae7160a9',
    messagingSenderId: '49160994700',
    projectId: 'tollo-on-flutter',
    authDomain: 'tollo-on-flutter.firebaseapp.com',
    storageBucket: 'tollo-on-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFG3XOf1aNttkLjEFxB3uhmr9wH5tGaE',
    appId: '1:49160994700:android:79609939c12297387160a9',
    messagingSenderId: '49160994700',
    projectId: 'tollo-on-flutter',
    storageBucket: 'tollo-on-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChOtlr2cpv1uerN1On82EnoT8RCxQmXQI',
    appId: '1:49160994700:ios:9e19fe9b131d8a5d7160a9',
    messagingSenderId: '49160994700',
    projectId: 'tollo-on-flutter',
    storageBucket: 'tollo-on-flutter.appspot.com',
    iosBundleId: 'com.example.tolloOnFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChOtlr2cpv1uerN1On82EnoT8RCxQmXQI',
    appId: '1:49160994700:ios:9e19fe9b131d8a5d7160a9',
    messagingSenderId: '49160994700',
    projectId: 'tollo-on-flutter',
    storageBucket: 'tollo-on-flutter.appspot.com',
    iosBundleId: 'com.example.tolloOnFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt81FYlfHiatIdpjsWx79mHPDCxSg8Zzg',
    appId: '1:49160994700:web:c7a86b190c398cca7160a9',
    messagingSenderId: '49160994700',
    projectId: 'tollo-on-flutter',
    authDomain: 'tollo-on-flutter.firebaseapp.com',
    storageBucket: 'tollo-on-flutter.appspot.com',
  );
}
