name: Flutter CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.1' # Specify the exact Flutter version
          cache: true

      - name: Install CocoaPods (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install cocoapods
          pod install --project-directory=ios
        continue-on-error: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --release
        continue-on-error: true

      - name: Build iOS (macOS only)
        if: runner.os == 'macOS'
        run: flutter build ios --release --no-codesign
        continue-on-error: true