name: Flutter CI

# Trigger the workflow on pull request and push to main or feature branches
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'

jobs:
  build-and-test:

    # Specify the matrix of operating systems
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Flutter on both Windows and macOS
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # For macOS, set up CocoaPods (needed for iOS builds)
      - name: Install CocoaPods (macOS only)
        if: runner.os == 'macOS'
        run: |
          brew install cocoapods
          pod install --project-directory=ios

      # Run flutter pub get to install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run tests for both platforms
      - name: Run Flutter Tests
        run: flutter test

      # Build for Android on both platforms (optional)
      - name: Build Android APK
        run: flutter build apk --release

      # Build for iOS only on macOS
      - name: Build iOS (macOS only)
        if: runner.os == 'macOS'
        run: flutter build ios --release

    # Firebase App Distribution (Optional, if you want to distribute builds)
    # You can add Firebase App Distribution steps here if needed.
